<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="template-generator" tests="25" assertions="38" failures="0" errors="1" time="0.194584">
    <testsuite name="NodeController_Test" file="/var/www/task_api/src/protected/tests/controllers/NodeController.php" tests="6" assertions="8" failures="0" errors="1" time="0.115632">
      <testsuite name="NodeController_Test::test_actionNodeCreate" tests="1" assertions="4" failures="0" errors="0" time="0.114364">
        <testcase name="test_actionNodeCreate with data set #0" assertions="4" time="0.114364"/>
      </testsuite>
      <testsuite name="NodeController_Test::test_actionNodeCreateFail" tests="4" assertions="4" failures="0" errors="0" time="0.001044">
        <testcase name="test_actionNodeCreateFail with data set #0" assertions="1" time="0.000379"/>
        <testcase name="test_actionNodeCreateFail with data set #1" assertions="1" time="0.000219"/>
        <testcase name="test_actionNodeCreateFail with data set #2" assertions="1" time="0.000223"/>
        <testcase name="test_actionNodeCreateFail with data set #3" assertions="1" time="0.000223"/>
      </testsuite>
      <testcase name="test_actionNodeList" class="NodeController_Test" file="/var/www/task_api/src/protected/tests/controllers/NodeController.php" line="148" assertions="0" time="0.000224">
        <error type="ReflectionException">NodeController_Test::test_actionNodeList
ReflectionException: Method actionList does not exist

/var/www/task_api/src/protected/vendor/fufu70/reflection-class/src/Reflection.php:137
/var/www/task_api/src/protected/vendor/fufu70/reflection-class/src/Reflection.php:44
/var/www/task_api/src/protected/tests/TestController.php:85
/var/www/task_api/src/protected/tests/TestController.php:54
/var/www/task_api/src/protected/tests/controllers/NodeController.php:150
</error>
      </testcase>
    </testsuite>
    <testsuite name="NodeMomentController_Test" file="/var/www/task_api/src/protected/tests/controllers/NodeMomentController.php" tests="8" assertions="14" failures="0" errors="0" time="0.030287">
      <testsuite name="NodeMomentController_Test::test_actionNodeMomentCreate" tests="1" assertions="7" failures="0" errors="0" time="0.028104">
        <testcase name="test_actionNodeMomentCreate with data set #0" assertions="7" time="0.028104"/>
      </testsuite>
      <testsuite name="NodeMomentController_Test::test_actionNodeMomentCreateFail" tests="7" assertions="7" failures="0" errors="0" time="0.002183">
        <testcase name="test_actionNodeMomentCreateFail with data set #0" assertions="1" time="0.000264"/>
        <testcase name="test_actionNodeMomentCreateFail with data set #1" assertions="1" time="0.000662"/>
        <testcase name="test_actionNodeMomentCreateFail with data set #2" assertions="1" time="0.000217"/>
        <testcase name="test_actionNodeMomentCreateFail with data set #3" assertions="1" time="0.000194"/>
        <testcase name="test_actionNodeMomentCreateFail with data set #4" assertions="1" time="0.000438"/>
        <testcase name="test_actionNodeMomentCreateFail with data set #5" assertions="1" time="0.000220"/>
        <testcase name="test_actionNodeMomentCreateFail with data set #6" assertions="1" time="0.000188"/>
      </testsuite>
    </testsuite>
    <testsuite name="TaskController_Test" file="/var/www/task_api/src/protected/tests/controllers/TaskController.php" tests="11" assertions="16" failures="0" errors="0" time="0.048665">
      <testcase name="test_actionIndex" class="TaskController_Test" file="/var/www/task_api/src/protected/tests/controllers/TaskController.php" line="153" assertions="1" time="0.004487"/>
      <testsuite name="TaskController_Test::test_actionTaskCreate" tests="1" assertions="4" failures="0" errors="0" time="0.011949">
        <testcase name="test_actionTaskCreate with data set #0" assertions="4" time="0.011949"/>
      </testsuite>
      <testsuite name="TaskController_Test::test_actionTaskCreateFail" tests="4" assertions="4" failures="0" errors="0" time="0.001091">
        <testcase name="test_actionTaskCreateFail with data set #0" assertions="1" time="0.000324"/>
        <testcase name="test_actionTaskCreateFail with data set #1" assertions="1" time="0.000317"/>
        <testcase name="test_actionTaskCreateFail with data set #2" assertions="1" time="0.000227"/>
        <testcase name="test_actionTaskCreateFail with data set #3" assertions="1" time="0.000223"/>
      </testsuite>
      <testcase name="test_actionTaskRequest" class="TaskController_Test" file="/var/www/task_api/src/protected/tests/controllers/TaskController.php" line="203" assertions="3" time="0.020909"/>
      <testsuite name="TaskController_Test::test_actionTaskRequestFail" tests="3" assertions="3" failures="0" errors="0" time="0.001043">
        <testcase name="test_actionTaskRequestFail with data set #0" assertions="1" time="0.000258"/>
        <testcase name="test_actionTaskRequestFail with data set #1" assertions="1" time="0.000221"/>
        <testcase name="test_actionTaskRequestFail with data set #2" assertions="1" time="0.000564"/>
      </testsuite>
      <testsuite name="TaskController_Test::test_actionTaskRequestNoTask" tests="1" assertions="1" failures="0" errors="0" time="0.009186">
        <testcase name="test_actionTaskRequestNoTask with data set #0" assertions="1" time="0.009186"/>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>
